### ISSUE TITLE
Console characters issue

### ISSUE THREAD

**Issue by szom1** [nirui/sshwifty#56] opened 2021-08-20 05:55 UTC
Hi,

When I start the app from Firefox, the "q" and "g" characters appear the same. The lower part of the characters are not visible. With Chrome this error does not occur.

![image](https://user-images.githubusercontent.com/88886839/130186510-25d1e056-35f4-4235-88d8-9b55e005964f.png)

**Comment by nirui** [comment] 2021-08-20 07:39
I'm afraid this is another thing that we have to wait.

The character issue was caused by a bug in a third-party component called `xtermjs`, which provides the console interface for Sshwifty. A dude has already pushed a patch to fix the problem, but the patch is still waiting to be accepted. See https://github.com/xtermjs/xterm.js/issues/3353

**Comment by nirui** [comment] 2021-11-06 13:15
The issue in the upstream component is fixed for Firefox, I have released version `0.2.17-beta` which included the updated component.

Closing the issue for now. Feel free to re-open it if needed.

**Closed by nirui** 2021-11-06 13:15 UTC
